name: Android CI

on:
  pull_request:
    branches:
    - develop
    - feature/*
    - release/*
    - hotfix/*    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle Packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate Keystore file from GitHub Secrets
      run: |
        mkdir ./app/signing
        echo "${{ secrets.KEYSTORE }}" | base64 -d > ./app/signing/keystore.jks
        echo "storeFile = $STOREFILE" >> ./app/signing/keystore.properties
        echo "keyAlias = $KEYALIAS" >> ./app/signing/keystore.properties
        echo "keyPassword = $KEYPASSWORD" >> ./app/signing/keystore.properties
        echo "storePassword = $STOREPASSWORD" >> ./app/signing/keystore.properties
      env:
        STOREFILE: ${{ secrets.STOREFILE }}
        KEYALIAS: ${{ secrets.KEYALIAS }}
        KEYPASSWORD: ${{ secrets.KEYPASSWORD }}
        STOREPASSWORD: ${{ secrets.STOREPASSWORD }}
    - name: Build with Gradle
      run: ./gradlew assembleDebug

