name: Android CI

on:
  pull_request:
    branches:
    - develop
    - feature/*
    - release/*
    - hotfix/*    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Cache Gradle Packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties', '**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Generate Keystore file from GitHub Secrets
      run: |
        echo "$KEYSTORE" > ./keystore.jks
        base64 -d -i ./keystore.jks
        echo "$KEYSTORE_PROPERTIES" > ./keystore.properties
        base64 -d -i ./keystore.properties

      env:
        KEYSTORE: ${{ secrets.KEYSTORE_BASE64 }}
        KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES_BASE64 }}
    - name: Build with Gradle
      run: ./gradlew build

